spring:
  datasource:
    username: root
    password: lh123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

  #thymeleaf start
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  #spring.thymeleaf.content-type过时
  #开发时关闭缓存,不然没法看到实时页面
  #thymeleaf end

  #发送邮件的配置
  mail:
    host: smtp.qq.com
    username: 2539203552@qq.com
    password: iemyjrwxhtbnebgc
    default-encoding: UTF-8


#spring.devtools.restart.enabled=true

mybatis:
  config-location: classpath:config/mybatis/mybatis_config.xml
  mapper-locations: classpath:config/mybatis/mappers/*.xml

# 打印sql
jwt:
  email:
    secret: fhjsk23343hfjrere74df #jwt的密钥,保证数据的完整性，避免被修改
    expire: 300  #密钥的过期时间,秒

email:
  fromMail:
    addr: 2539203552@qq.com
  valid:
    href: http://localhost:8082/email/validEmail/

logging:
  path: F:/spring-boot/blog/log/
  level:
   web: INFO
   com.lhuang.blog.user.provider.dao: debug
   org.springframework.web: INFO
   org.hibernate: ERROR

server:
  port: 8082

rocketmq:
  name-server: 122.51.109.121:9876
  producer:
   group: produce_group
   sendMessageTimeout: 300000



